### ISSUE TITLE
VAE's training data

### ISSUE THREAD

**Issue by hkchengrex** [bytedance/Make-An-Audio-2#5]
Hi, thank you for the great work and the code.

In the paper, it is mentioned that the VAE is trained on the filtered AudioSet subset. In the code, the configuration file points "spec_dir_path" to "ldm/data/tsv_dirs/full_data/V1_new" -- I am wondering if they refer to the same data? 

Thanks, and best, 
Rex

**Comment by Darius-H** [comment]
Yes, the VAE is trained on filtered AudioSet subset

**Comment by hkchengrex** [comment]
Thanks!

**Comment by CrossLee1** [comment]
Hi, what is the filetering strategy to get the audioset subset.
Could you provide the filtered youtube ids? thanks
